(() => {
 'use strict';
 const $=id=>document.getElementById(id), alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
 let config={case:'upper',length:12,pop:2800,duration:18,hint:false,sound:true};
 try{const raw=JSON.parse(localStorage.getItem('abc-duel-v1')||'null');if(raw){if(['upper','lower','mixed'].includes(raw.case))config.case=raw.case;if([12,26].includes(raw.length))config.length=raw.length;if([2000,2800,4000].includes(raw.pop))config.pop=raw.pop;if([12,18,25].includes(raw.duration))config.duration=raw.duration;if(typeof raw.hint==='boolean')config.hint=raw.hint;if(typeof raw.sound==='boolean')config.sound=raw.sound;}}catch{}
 const player=()=>({score:0,hits:0,misses:0,locked:0,solved:false,slots:Array(9).fill(null),popIn:0,message:'Find the letter when it pops up!',boost:0});
 const state={mode:'menu',round:0,target:'',deck:[],remaining:0,countdown:0,transition:0,elapsed:0,players:[player(),player()],paused:false};
 let raceConfig={...config},last=performance.now(),manual=false,audio=null;const canvas=$('track'),ctx=canvas.getContext('2d');
 function shuffle(values){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function save(){try{localStorage.setItem('abc-duel-v1',JSON.stringify(config));}catch{}}
 function speak(){if(!config.sound||!state.target||state.paused)return;if(!('speechSynthesis'in window)){raceConfig.hint=true;render();return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`Find the letter ${state.target.toUpperCase()}.`);u.lang='en-US';u.rate=.85;u.pitch=1.08;u.voice=speechSynthesis.getVoices().find(v=>v.lang==='en-US')||null;u.onerror=e=>{if(e.error!=='canceled'&&e.error!=='interrupted'){raceConfig.hint=true;render();}};speechSynthesis.speak(u);}
 function tone(good){if(!config.sound)return;try{audio ||= new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.setValueAtTime(good?660:260,audio.currentTime);o.frequency.exponentialRampToValueAtTime(good?990:220,audio.currentTime+.15);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);o.start();o.stop(audio.currentTime+.22);}catch{}}
 function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
 function start(){closeDialogs();raceConfig={...config};Object.assign(state,{mode:'countdown',round:0,target:'',deck:shuffle(alphabet),remaining:0,countdown:3,transition:0,elapsed:0,players:[player(),player()],paused:false});document.body.classList.add('running');$('pause').disabled=false;render();}
 function newRound(){state.mode='race';state.round++;if(state.round>raceConfig.length){finish();return;}const upper=state.deck[state.round-1];state.target=raceConfig.case==='lower'||raceConfig.case==='mixed'&&state.round%2===0?upper.toLowerCase():upper;state.remaining=raceConfig.duration;state.transition=0;for(const p of state.players){p.solved=false;p.popIn=0;p.message=p.locked>0?'Your pit stop is almost over!':'Find the letter when it pops up!';p.boost=0;}populate();render();speak();}
 function populate(which){const lower=state.target===state.target.toLowerCase();const bank=lower?alphabet.map(v=>v.toLowerCase()):alphabet;const letters=[state.target,...shuffle(bank.filter(l=>l!==state.target)).slice(0,4)];for(let i=0;i<2;i++){if(which!==undefined&&i!==which)continue;const p=state.players[i];if(p.solved)continue;const positions=shuffle([0,1,2,3,4,5,6,7,8]);const previous=p.slots.indexOf(state.target);if(positions[0]===previous)[positions[0],positions[1]]=[positions[1],positions[0]];p.slots=Array(9).fill(null);letters.forEach((l,j)=>p.slots[positions[j]]=l);p.popIn=raceConfig.pop/1000;renderBoard(i);}}
 function hit(i,slot){const p=state.players[i];if(state.mode!=='race'||state.paused||p.locked>0||p.solved||state.transition>0||!p.slots[slot])return;if(p.slots[slot]!==state.target){p.locked=5;p.misses++;p.message='Good try! A 5-second pit stop, then go again.';tone(false);}else{p.solved=true;p.hits++;p.score+=10;p.boost=1.5;p.message='Yes! +10 points. Turbo boost!';tone(true);if(state.players.every(p=>p.solved))state.transition=1.3;}render();}
 for(let i=0;i<2;i++){for(let j=0;j<9;j++){const b=document.createElement('button');b.className='hole empty';b.innerHTML='<span class="mole"></span>';b.dataset.slot=j;b.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();hit(i,j);});b.addEventListener('click',e=>{if(e.detail===0)hit(i,j);});$('board-'+i).append(b);}}
 function renderBoard(i){const p=state.players[i];[...$('board-'+i).children].forEach((b,j)=>{const letter=p.slots[j];const cls='hole'+(!letter?' empty':'')+(p.solved&&letter===state.target?' scored':'');if(b.className!==cls)b.className=cls;const span=b.querySelector('span');if(span.textContent!==(letter||''))span.textContent=letter||'';b.disabled=state.mode!=='race'||state.paused||p.locked>0||p.solved||!letter;b.setAttribute('aria-label',`Player ${i+1}, hole ${j+1}${letter?': letter '+letter:': empty'}`);});}
 function render(){const race=state.mode==='race';$('sound').textContent=config.sound?'♫ Sound on':'♫ Sound off';$('round-label').textContent=state.mode==='menu'?'SMART BOARD SHOWDOWN':`LETTER ROUND ${Math.min(state.round,raceConfig.length)} / ${raceConfig.length}`;$('prompt').textContent=race?raceConfig.hint||!config.sound?`Find the letter ${state.target}!`:'Listen! Find the letter.':state.mode==='countdown'?'Ready, racers?':state.mode==='finish'?'What a brilliant race!':'Listen. Spot it. Tap it!';$('round-clock').textContent=race?state.transition>0?'Next letter…':`${Math.ceil(state.remaining)} seconds`:state.mode==='menu'?`${config.length} letter rounds`:state.mode==='finish'?'🏁 FINISH':'Ready, set…';$('listen').disabled=!race||state.paused;$('pause').textContent=state.paused?'▶ Resume':'Ⅱ Pause';$('countdown').hidden=state.mode!=='countdown';$('countdown').querySelector('b').textContent=Math.max(1,Math.ceil(state.countdown));for(let i=0;i<2;i++){const p=state.players[i];$('score-'+i).textContent=p.score;$('message-'+i).textContent=p.message;$('lock-'+i).hidden=p.locked<=0||!race;$('lock-clock-'+i).textContent=Math.ceil(p.locked);$('player-'+i).classList.toggle('solved',p.solved);renderBoard(i);}draw();}
 function update(dt){if(state.paused)return;state.elapsed+=dt;if(state.mode==='countdown'){state.countdown-=dt;if(state.countdown<=0)newRound();return;}if(state.mode!=='race')return;for(let i=0;i<2;i++){const p=state.players[i],before=p.locked;p.locked=Math.max(0,p.locked-dt);p.boost=Math.max(0,p.boost-dt);if(before>0&&p.locked===0)p.message='Pit stop over. You can tap again!';if(!p.solved){p.popIn-=dt;if(p.popIn<=0)populate(i);}}if(state.transition>0){state.transition-=dt;if(state.transition<=0)newRound();}else{state.remaining=Math.max(0,state.remaining-dt);if(state.remaining===0)newRound();}}
 function finish(){state.mode='finish';$('pause').disabled=true;for(const p of state.players){p.locked=0;p.message='Fantastic learning, racer!';}const [a,b]=state.players;const tied=a.score===b.score;$('winner').textContent=tied?'Two alphabet champions!':`${a.score>b.score?'Sunshine':'Ocean'} racers win!`;$('result-description').textContent=`${raceConfig.length} letters raced! Both racers learned and zoomed. Great teamwork!`;$('result-0').textContent=a.score;$('result-1').textContent=b.score;render();$('results').showModal();try{const old=JSON.parse(localStorage.getItem('abc-racing-v1')||'{}');old.races=(Number(old.races)||0)+1;localStorage.setItem('abc-racing-v1',JSON.stringify(old));}catch{}}
 function menu(){closeDialogs();state.mode='menu';state.paused=false;state.target='';state.players=[player(),player()];$('pause').disabled=true;document.body.classList.remove('running');render();$('welcome').showModal();}
 function pause(show=true){if(!['race','countdown'].includes(state.mode))return;state.paused=!state.paused;if(state.paused){if('speechSynthesis'in window)speechSynthesis.cancel();if(show)$('pause-dialog').showModal();}else{if($('pause-dialog').open)$('pause-dialog').close();speak();}render();}
 function settings(){if($('welcome').open)$('welcome').close();if(['race','countdown'].includes(state.mode)&&!state.paused)pause(false);$('letter-case').value=config.case;$('race-length').value=config.length;$('pop-speed').value=config.pop;$('round-duration').value=config.duration;$('visual-hint').checked=config.hint;$('settings-dialog').showModal();}
 function settingsClosed(){if(state.mode==='menu')$('welcome').showModal();else if(state.paused)$('pause-dialog').showModal();render();}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{}}
 function draw(){const w=1600;ctx.clearRect(0,0,w,90);ctx.fillStyle='#c6dcb0';ctx.fillRect(0,0,w,90);ctx.fillStyle='#718877';ctx.fillRect(0,14,w,64);ctx.fillStyle='#e9eccc';for(let i=0;i<32;i++)ctx.fillRect(i*60-(state.elapsed*30)%60,44,30,3);ctx.font='bold 13px Nunito';ctx.fillStyle='#fff8d7';ctx.fillText('START',15,10);ctx.fillText('FINISH',1515,10);for(let j=0;j<5;j++)for(let k=0;k<4;k++){ctx.fillStyle=(j+k)%2?'#fff8de':'#32574b';ctx.fillRect(1550+j*9,14+k*16,9,16);}state.players.forEach((p,i)=>{const x=35+p.score/(raceConfig.length*10)*1435,y=i===0?28:61;ctx.fillStyle='#25433733';ctx.beginPath();ctx.ellipse(x+5,y+11,29,6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=i===0?'#ffce4c':'#72cee1';ctx.beginPath();ctx.roundRect(x-25,y-12,50,22,8);ctx.fill();ctx.fillStyle='#eaf6ed';ctx.fillRect(x-10,y-9,14,16);ctx.fillStyle='#254a45';ctx.fillRect(x-18,y-15,12,5);ctx.fillRect(x-18,y+9,12,5);ctx.fillRect(x+10,y-15,12,5);ctx.fillRect(x+10,y+9,12,5);if(p.boost>0){ctx.fillStyle='#ffed80';ctx.beginPath();ctx.moveTo(x-25,y-7);ctx.lineTo(x-47-Math.sin(state.elapsed*20)*5,y);ctx.lineTo(x-25,y+7);ctx.fill();}});}
 function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!manual)update(dt);render();requestAnimationFrame(frame);}
 window.advanceTime=ms=>{manual=true;for(let t=0;t<ms;t+=16.667)update(Math.min(16.667,ms-t)/1000);render();};
 window.render_game_to_text=()=>JSON.stringify({mode:state.mode,paused:state.paused,round:state.round,rounds:raceConfig.length,target:state.target,remaining:state.remaining,countdown:state.countdown,transition:state.transition,coordinateSystem:'Each board has 9 holes: indices 0–8, row-major from top left, three rows and three columns',players:state.players.map(p=>({score:p.score,hits:p.hits,misses:p.misses,lockoutSeconds:p.locked,solved:p.solved,holes:p.slots,secondsUntilPop:p.popIn})),config:raceConfig});
 $('start').onclick=start;$('start-fullscreen').onclick=()=>{fullscreen();start();};$('again').onclick=start;$('restart').onclick=()=>{if(state.mode==='menu')start();else{if(!state.paused)pause();}};$('paused-restart').onclick=start;$('menu').onclick=menu;$('listen').onclick=speak;$('pause').onclick=()=>pause();$('resume').onclick=()=>pause();$('fullscreen').onclick=fullscreen;$('settings').onclick=settings;$('welcome-settings').onclick=settings;$('cancel-settings').onclick=()=>{$('settings-dialog').close();settingsClosed();};$('save-settings').onclick=()=>{config.case=$('letter-case').value;config.length=Number($('race-length').value);config.pop=Number($('pop-speed').value);config.duration=Number($('round-duration').value);config.hint=$('visual-hint').checked;save();$('settings-dialog').close();settingsClosed();};$('sound').onclick=()=>{config.sound=!config.sound;save();if(!config.sound&&'speechSynthesis'in window)speechSynthesis.cancel();if(config.sound)speak();render();};
 for(const id of ['welcome','pause-dialog','results'])$(id).addEventListener('cancel',e=>e.preventDefault());$('settings-dialog').addEventListener('cancel',()=>{setTimeout(settingsClosed,0);});
 document.addEventListener('keydown',e=>{if(e.target.matches('select,input'))return;if(e.key.toLowerCase()==='f'){fullscreen();return;}if(e.key==='Escape'&&!document.querySelector('dialog[open]'))pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!state.paused)pause();});
 menu();requestAnimationFrame(frame);
})();
