process.chdir(require('node:path').resolve(__dirname,'..'));
const {chromium}=require('./test-runtime.cjs');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{fs.mkdirSync('alphabet-racing/output/duel',{recursive:true});const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1920,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:5188/alphabet-racing/');await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'alphabet-racing/output/duel/welcome.png'});await page.locator('#start').click();await page.evaluate(()=>advanceTime(3100));const state=()=>page.evaluate(()=>JSON.parse(render_game_to_text()));const advance=ms=>page.evaluate(ms=>advanceTime(ms),ms);const hit=async(i,letter)=>{const s=await state();const j=s.players[i].holes.indexOf(letter);assert.ok(j>=0);await page.locator(`#board-${i} .hole`).nth(j).dispatchEvent('pointerdown',{button:0,pointerType:'touch',pointerId:i+1});};
 let s=await state();assert.equal(s.mode,'race');assert.equal(await page.locator('.hole').count(),18);assert.equal(s.players[0].holes.filter(Boolean).length,5);const area=await page.locator('.arena').boundingBox();assert.ok(area.height>=1080*.65);await page.waitForTimeout(250);await page.screenshot({path:'alphabet-racing/output/duel/boards.png'});
 const old=s.players[0].holes.indexOf(s.target);await advance(2900);s=await state();assert.notEqual(s.players[0].holes.indexOf(s.target),old);
 await hit(0,s.players[0].holes.find(l=>l&&l!==s.target));s=await state();assert.equal(s.players[0].lockoutSeconds,5);await page.screenshot({path:'alphabet-racing/output/duel/lockout.png'});await hit(0,s.target);assert.equal((await state()).players[0].score,0);await hit(1,s.target);assert.equal((await state()).players[1].score,10);await hit(1,s.target);assert.equal((await state()).players[1].score,10);
 await advance(4900);s=await state();assert.ok(s.players[0].lockoutSeconds>0);await hit(0,s.target);assert.equal((await state()).players[0].score,0);await page.locator('#pause').click();await advance(10000);assert.equal((await state()).players[0].lockoutSeconds,s.players[0].lockoutSeconds);await page.locator('#resume').click();await advance(110);assert.equal((await state()).players[0].lockoutSeconds,0);s=await state();await hit(0,s.target);assert.equal((await state()).players[0].score,10);await advance(1400);assert.equal((await state()).round,2);
 // Both physical touch pointers can hit independently in the same frame.
 s=await state();await page.evaluate(s=>{for(let i=0;i<2;i++)document.querySelectorAll('#board-'+i+' .hole')[s.players[i].holes.indexOf(s.target)].dispatchEvent(new PointerEvent('pointerdown',{button:0,pointerType:'touch',pointerId:10+i,bubbles:true}));},s);s=await state();assert.ok(s.players.every(p=>p.score===20));await advance(1400);
 // Timer can advance without answers. Lockout survives a round boundary.
 await advance(17900);s=await state();await hit(0,s.players[0].holes.find(l=>l&&l!==s.target));await advance(200);assert.equal((await state()).round,4);assert.ok((await state()).players[0].lockoutSeconds>4);await advance(5000);
 while((await state()).mode==='race'){s=await state();await hit(0,s.target);await hit(1,s.target);await advance(1400);}
 s=await state();assert.equal(s.mode,'finish');assert.equal(s.players[0].score,s.players[1].score);await page.screenshot({path:'alphabet-racing/output/duel/results.png'});await page.locator('#again').click();await advance(3100);assert.equal((await state()).players[0].score,0);await page.locator('#settings').click();await page.locator('#letter-case').selectOption('lower');await page.locator('#race-length').selectOption('26');await page.locator('#visual-hint').check();await page.locator('#save-settings').click();await page.locator('#paused-restart').click();await advance(3100);assert.match((await state()).target,/^[a-z]$/);assert.equal((await state()).rounds,26);assert.match(await page.locator('#prompt').innerText(),/Find the letter [a-z]/);await page.locator('#fullscreen').click();await page.waitForFunction(()=>!!document.fullscreenElement);await page.locator('#fullscreen').click();await page.waitForFunction(()=>!document.fullscreenElement);
 await page.setViewportSize({width:1280,height:720});await page.screenshot({path:'alphabet-racing/output/duel/board-720.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight));await page.setViewportSize({width:390,height:844});await page.screenshot({path:'alphabet-racing/output/duel/mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight));assert.deepEqual(errors,[]);fs.writeFileSync('alphabet-racing/output/duel/results.json',JSON.stringify({passed:true,checks:['18 large holes','target relocation','5-second player-only lockout','spam ignored','other player scores during lockout','one hit per round','pause freezes timers','simultaneous touch','timer advances rounds','lock persists across rounds','finish tie','restart','teacher settings','fullscreen','720p and mobile viewport'],errors},null,2));console.log('PASS: two-player boards, exact 5-second lockout, independent touch, timers, full race, restart, settings and layouts.');await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
